### PR TITLE
Includes improvements related to containerized workflows.

### LINKED ISSUE #242: Enable diagnostics logging to go to either syslog or stdout
### Expected behavior
When specifying the -log switch allow a choice of the target being either syslog or stdout.

### Actual behavior
Diagnostics logging when using -log goes to syslog.

### Steps to reproduce the behavior
1. Run procdump with the -log switch. 

### System information (e.g., distro, kernel version, etc.)
N/A

### PR DESCRIPTION
**Pull request by MarioHewardt**
Fixes #242 #243 #244 #245 #246 #248 #249

### CODE REVIEW

File: ebpf/procdump_ebpf.c [hunk 1]
```diff
@@ -66,52 +93,57 @@ static inline void ZeroMemory(char* ptr, unsigned int size)
...
     if (event == NULL)
     {
-        BPF_PRINTK("[SendEvent] Failed: Getting event (allocation address: 0x%lx, target PID: %d)\n", alloc, target_PID);
+        BPF_PRINTK("   [SendEvent] Failed: Getting event (allocation address: 0x%lx, target PID: %d)", alloc, target_PID);
         return 1;
     }
 
     //
-    // Set the allocation address
+    // Set the allocation address if its an allocation operation
```
Comment (johnstep) [inline ebpf/procdump_ebpf.c]: `it's` or `it is`
